### ISSUE TITLE
Is it correct to initialize this here and not before?

### ISSUE THREAD

**Issue by ChrisS85** [unicfdlab/hybridCentralSolvers#1]
Question concerning 
https://github.com/unicfdlab/hybridCentralSolvers/blob/c3ecfa63041d3ee3ecadf8c49226f3196e2d48e6/OpenFOAM-4.1/pisoCentral/commonIncludes/createCommonCentralFields.H#L122

psiU_nei depends on psi_nei, should it not be affected by this correction? Just wondering while looking through the code...

**Comment by unicfdlab** [comment]
The function correctCentralACMIInterpolation ensures that field (psi_nei in this part of the code is not zero) because to get U_nei we use psiU_nei / psi_nei
