### ISSUE TITLE
Openfoam-v1706

### ISSUE THREAD

**Issue by jhierroa** [unicfdlab/hybridCentralSolvers#2]
I have modified version 4.1 of these solvers so that they may work with version v1706.

Most important changes come from the need to use some orientedType variables. In particular cSf_own.setOriented(true) and cSf_nei.setOriented(true) in createCommonCentralFields; aSf.setOriented(false) after the second call to updateKappa.H in reactingPimpleCentralFoam.C.

dQ and Sh have been supressed (Sh is now Qdot, dQ has dissapeared). 

There has been also some changes in capital letters of the names of some thermodynamic variables and betaSolidIO.headerOk() has been replaced by
betavSolidIO.typeHeaderOk<volScalarField>(true) in createSolidFields.H.

**Comment by unicfdlab** [comment]
Hi, good news!
Did you test solver with all tests from Tutorials solver?
Do you have plans to include changes in this repository?

**Comment by unicfdlab** [comment]
OpenFOAM+ version 1812 of hybridCentralSolvers is issued - see branch digitef-dev-1812
