### ISSUE TITLE
pisoCentral OF6

### ISSUE THREAD

**Issue by atedalv** [unicfdlab/hybridCentralSolvers#4]
Is there a pisoCentral in of6-dev branch or it will be included later on for OF6? Thanks

**Comment by unicfdlab** [comment]
Hi, pisoCentralFoam was replaced with pimpleCentralFoam.
However, you can reproduce PISO scheme within pimpleCentralFoam by setting
nOuterCorrectors to 1
and nCorrectors to 1 or more PISO correctors

**Comment by atedalv** [comment]
Thanks a lot for clarification.
