### ISSUE TITLE
How to implement QGDFoam's readScNumbers.H to reactingPimpleCentralFoam?

### ISSUE THREAD

**Issue by scramjetFoam** [unicfdlab/hybridCentralSolvers#50]
Hi,

I have seen the implementation of different Schmidt numbers in QGDFoam which is an intersting feature. How can it be implemented in reactingPimpleCentralFoam? Because I am not very familiar with programming. Thank you in advance.

Regards.

**Comment by mkraposhin** [comment]
Hi, it should be simple. You have to read Sc numbers from some dictionary and then apply them mass fraction transport equations are solved

**Comment by mkraposhin** [comment]
There is a code in file readScNumbers.H (QGD) that reads Sc constant values in array (one value per each component of the flow).
Advection-Diffusion equation in reactingPimpleCentralFoam is solved in YEqn.H. It's diffusion part is approximated here:
`            fvScalarMatrix YDiffusion
            (
                - fvm::laplacian(mDCf[iCmpt], Yi)
            );
`

**Comment by scramjetFoam** [comment]
Roger it. Thank you.
