### ISSUE TITLE
Compiling pimpleCentralFoam problem on openfoam v1912

### ISSUE THREAD

**Issue by atenamsv** [unicfdlab/hybridCentralSolvers#7]
I'm currently try to compile pimpleCentralFoam on openfoam v1912 and i receive errors regarding -lpisoCentral, or something. i found the pimpleCentral folder for v1912 a little bit disordered. like there is no pimpleCentralFoam.C for this version. can anyone help?
https://photos.google.com/share/AF1QipPCJzUh3tNCRMd58VS6FT9gk253k51eC68txPeuewwumJaL3dEW8z5lwPHZz6dUgQ?key=dUF0eVVIZWxWVUZYY29nejQwMlotWExDZU5VeWhR

**Comment by unicfdlab** [comment]
Hello, it looks like you have downloaded version from the wrong branch, because in the **digitef-dev-1912** branch, which corresponds to OpenFOAM+1912 we don't have any links to -lpisoCentral, see  [https://github.com/unicfdlab/hybridCentralSolvers/tree/digitef-dev-1912](https://github.com/unicfdlab/hybridCentralSolvers/tree/digitef-dev-1912) file Sources/pimpleCentralFoam/Make/options:

`    -L$(FOAM_USER_LIBBIN) \
    -lpimpleCentral \
    -lfiniteVolume \
    -lfluidThermophysicalModels \
    -lspecie \
    -lturbulenceModels \
    -lcompressibleTransportModels \
    -lcompressibleTurbulenceModels \
    -lmeshTools \
    -lfvOptions`

**Comment by atenamsv** [comment]
Thanks for your reply. That was the problem, but still I have an error while compiling rhoPimpleCentralFoam. I tried to compile rhoPimpleCentralFoam, but I receive this error:

/usr/bin/ld: cannot open output file /opt/OpenFOAM/OpenFOAM-v1912/platforms/linux64GccDPInt320pt/bin/rhoPimpleCentralFoam: Permission denied
collect2: ld returned 1 exit status
make: *** [/opt/OpenFOAM/OpenFOAM-v1912/platforms/linux64GccDPInt320pt/bin/rhoPimpleCentralFoam] Error 1

**Comment by unicfdlab** [comment]
Hi, it looks like you are trying to write into protected (system) folder. You must switch the destination folder of the  _hybridCentralSolvers_ project binaries. In the root of the repository's branch you will find scrpit **SwitchDest** . This script allows to switch destination of binary files (executables and libraries) . Run:

> ./SwitchDest USER

to set PATH for _hybridCentralSolvers_ executables to $FOAM_USER_APPBIN

>./SwitchDest 

to set PATH for _hybridCentralSolvers_ executables to $FOAM_APPBIN

**Comment by atenamsv** [comment]
Thanks for your quick answer. Unfortunately, I did what you advised me, Downloaded v1912 files, called ./SwitchDest User and then tried to compile, but i still have errors (see photoes)
![image](https://user-images.githubusercontent.com/66470454/84033399-12e04700-a999-11ea-94bf-ed70cfe96e78.png)
![image](https://user-images.githubusercontent.com/66470454/84033437-22f82680-a999-11ea-8b53-b745ce3bf795.png)

**Comment by unicfdlab** [comment]
As the first step, can you switch your console to English before running commands:

> export LC_ALL=C

**Comment by unicfdlab** [comment]
Then, run

> Allwclean

**Comment by unicfdlab** [comment]
> Allwmake

**Comment by atenamsv** [comment]
Thanks a lot for your kind help, It works now.
